"""Motion is an editorial walkthrough of the approved canon, not generated science."""
import hashlib
from html.parser import HTMLParser
import json
from pathlib import Path
import re
import unittest

ROOT=Path(__file__).resolve().parents[1]
SKILL=ROOT/'skills/mechanism-figures'


class MotionHTML(HTMLParser):
    def __init__(self):
        super().__init__();self.images=[];self.scenes=[];self.ids=[];self.sections=[];self.story_images=[]
    def handle_starttag(self,tag,attrs):
        a=dict(attrs)
        if tag=='section':self.sections.append(a.get('id'))
        if a.get('id'):self.ids.append(a['id'])
        if 'data-scene' in a:self.scenes.append(a['data-scene'])
        if tag=='img':
            self.images.append(a['src'])
            if 'how-it-works' in self.sections:self.story_images.append(a['src'])
    def handle_endtag(self,tag):
        if tag=='section' and self.sections:self.sections.pop()


class MotionTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.registry=json.loads((SKILL/'assets/calibration.json').read_text())
        cls.story=json.loads((SKILL/'assets/motion-story.json').read_text())
    def parse(self,name):
        p=MotionHTML();p.feed((SKILL/'assets'/name).read_text());return p
    def test_both_routes_contain_all_six_workflow_scenes(self):
        for file in ['gallery.html','motion.html']:
            self.assertEqual(self.parse(file).scenes,[str(i) for i in range(6)])
    def test_scientific_pixels_are_only_existing_approved_assets(self):
        approved={a['path'] for r in self.registry['references'] for a in r['assets']}
        for name in ['gallery.html','motion.html']:
            p=self.parse(name);self.assertEqual(len(p.story_images),10)
            for src in p.story_images:self.assertIn('assets/'+src,approved)
    def test_story_manifest_binds_reference_asset_hashes(self):
        self.assertEqual(len(self.story['assets']),6)
        registry={(r['id'],a['path']):a['sha256'] for r in self.registry['references'] for a in r['assets']}
        for a in self.story['assets']:
            self.assertEqual(a['sha256'],registry[(a['reference'],a['asset'])])
            self.assertEqual(a['sha256'],hashlib.sha256((SKILL/a['asset']).read_bytes()).hexdigest())
    def test_no_unresolved_build_markers(self):
        for file in ['gallery.html','motion.html']:self.assertNotIn('@@',(SKILL/'assets'/file).read_text())
    def test_controls_have_unique_ids(self):
        required={'motion-play','motion-replay','motion-seek','motion-mode','how-it-works','world-link'}
        for name in ['gallery.html','motion.html']:
            p=self.parse(name);self.assertEqual(len(p.ids),len(set(p.ids)));self.assertTrue(required.issubset(p.ids))
    def test_published_target_not_claimed_as_skill_output(self):
        s=(SKILL/'assets/motion.html').read_text()
        self.assertIn('not a live agent run',s)
        self.assertIn('not figures generated by this skill',s)
        self.assertIn('RELEASE POLICY, NOT A LIVE SCORE',s)
    def test_reduced_motion_and_text_alternative_are_shipped(self):
        s=(SKILL/'assets/motion.html').read_text()
        self.assertIn('prefers-reduced-motion: reduce',s)
        self.assertIn('Read the walkthrough',s)
        self.assertIn('Animation timeline',s)
    def test_original_gallery_is_not_replaced(self):
        p=self.parse('gallery.html');self.assertEqual(len(p.images)-len(p.story_images),21)
        self.assertEqual(len(self.registry['references']),20)
        self.assertEqual(sum(len(r['assets']) for r in self.registry['references']),29)
    def test_no_remote_image_or_script_dependencies(self):
        p=self.parse('motion.html')
        self.assertTrue(all(not src.startswith(('http:','https:','data:')) for src in p.images))
        s=(SKILL/'assets/motion.html').read_text()
        self.assertNotRegex(s,r'<script[^>]+src=')
    def test_release_duration_and_policy_explicit(self):
        self.assertEqual(self.story['duration_seconds'],60)
        self.assertEqual(self.story['chapters'],['Question','Study','Construct','Critique','Deliver','Possibilities'])
        self.assertIn('instructional policy',self.story['status_policy'])


if __name__=='__main__':unittest.main()
