"use strict";
const CALIBRATION=JSON.parse(document.getElementById('calibration-data').textContent);
const refs=Object.fromEntries(CALIBRATION.references.map(r=>[r.id,r]));
let group='all',current=null,currentAsset=null,native=false,previousFocus=null;
const search=document.getElementById('search'),viewer=document.getElementById('viewer');
function applyFilters(){let n=0;const query=search.value.trim().toLowerCase();document.querySelectorAll('article').forEach(a=>{const match=(group==='all'||a.dataset.group===group)&&a.textContent.toLowerCase().includes(query);a.hidden=!match;if(match)n++;});document.getElementById('count').textContent=n+' of 20 references';document.getElementById('empty').hidden=n>0;}
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{group=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));applyFilters();}));search.addEventListener('input',applyFilters);
function renderViewer(){const r=refs[current],host=document.getElementById('viewer-images');host.replaceChildren();const selected=currentAsset?[currentAsset]:r.display_assets;host.className=(native?'native':'')+(selected.length>1?' multiple':'');for(const p of selected){const image=document.createElement('img');image.src=p.replace(/^assets\//,'');image.alt=r.label+' — '+r.display_figure;host.append(image);}document.getElementById('viewer-title').textContent=r.label+' · '+r.display_figure;document.getElementById('fit').setAttribute('aria-pressed',String(native));document.getElementById('fit').textContent=native?'Fit to view':'Native size';const choices=document.getElementById('viewer-choices');choices.replaceChildren();for(const a of r.assets){const b=document.createElement('button');b.type='button';b.textContent=a.kind==='related'?'Related figure':a.kind.charAt(0).toUpperCase()+a.kind.slice(1)+' figure';b.setAttribute('aria-pressed',String(selected.includes(a.path)));b.addEventListener('click',()=>{currentAsset=a.path;native=false;renderViewer();});choices.append(b);}document.getElementById('viewer-credit').textContent=r.authors+' · '+r.venue+' '+r.year+'. '+r.assets.filter(a=>selected.includes(a.path)).map(a=>a.treatment).join(' ');}
function openViewer(id,asset=null){if(!refs[id])return;previousFocus=document.activeElement;current=id;currentAsset=asset;native=false;renderViewer();viewer.showModal();document.body.style.overflow='hidden';}
document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openViewer(b.dataset.open,b.dataset.asset||null)));
document.getElementById('fit').addEventListener('click',()=>{native=!native;renderViewer();});document.getElementById('close').addEventListener('click',()=>viewer.close());viewer.addEventListener('close',()=>{document.body.style.overflow='';if(previousFocus?.isConnected)previousFocus.focus({preventScroll:true});});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&viewer.open){e.preventDefault();viewer.close();}});viewer.addEventListener('click',e=>{if(e.target===viewer){const b=viewer.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)viewer.close();}});
